# Generated by Django 6.0.7 on 2026-07-23 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalidad_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sistema_en_mantenimiento', models.BooleanField(default=False)),
                ('mensaje_mantenimiento', models.TextField(default='Estamos actualizando Mentalidad Clara para ti. Vuelve pronto.')),
            ],
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('PACIENTE', 'Paciente'), ('TERAPEUTA', 'Terapeuta'), ('ADMIN', 'Administrador')], default='PACIENTE', max_length=20),
        ),
        migrations.CreateModel(
            name='ReporteModeracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('administrador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_creados', to=settings.AUTH_USER_MODEL)),
                ('usuario_reportado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_recibidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
