# Generated by Django 6.0.7 on 2026-07-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalidad_app', '0003_disponibilidadterapeuta'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/'),
        ),
    ]
