# Generated by Django 6.0.7 on 2026-07-24 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalidad_app', '0005_actividademocional'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='pin_diario',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
