# Generated by Django 6.0.7 on 2026-07-24 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalidad_app', '0006_perfilusuario_pin_diario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividademocional',
            name='emocion_objetivo',
            field=models.CharField(blank=True, choices=[('FELIZ', 'Feliz / Motivado'), ('ANSIOSO', 'Ansioso / Preocupado'), ('FRUSTRADO', 'Frustrado / Incomodo'), ('TRISTE', 'Triste / Desanimado'), ('ESTRESADO', 'Estresado / Saturado'), ('NEUTRAL', 'Neutral / Tranquilo')], default='ANSIOSO', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('disponible', models.BooleanField(default=True)),
                ('paciente', models.ForeignKey(blank=True, limit_choices_to={'perfil__rol': 'PACIENTE'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios_asignados', to=settings.AUTH_USER_MODEL)),
                ('terapeuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_creados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
