# Generated by Django 6.0.7 on 2026-07-24 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalidad_app', '0008_notaclinica_delete_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='especialidad',
            field=models.CharField(blank=True, choices=[('Psicología Infantil', 'Psicología Infantil'), ('Psicología Clínica', 'Psicología Clínica'), ('Terapia Cognitivo-Conductual', 'Terapia Cognitivo-Conductual'), ('Terapia Familiar y de Pareja', 'Terapia Familiar y de Pareja'), ('Neuropsicología', 'Neuropsicología'), ('Psicopedagogía', 'Psicopedagogía'), ('Psicoterapia Humanista', 'Psicoterapia Humanista'), ('Psicología Educativa', 'Psicología Educativa')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
