# Generated by Django 6.0.7 on 2026-07-24 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalidad_app', '0010_actividad_fecha_creacion_actividad_paciente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteComportamientoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_comportamiento', models.CharField(choices=[('Falta de Asistencia / Incumplimiento', 'Falta de Asistencia / Incumplimiento'), ('Resistencia al Tratamiento', 'Resistencia al Tratamiento'), ('Conducta Disruptiva o Inapropiada', 'Conducta Disruptiva o Inapropiada'), ('Incumplimiento de Actividades', 'Incumplimiento de Actividades'), ('Otro', 'Otro')], max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_comportamiento', to=settings.AUTH_USER_MODEL)),
                ('terapeuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_emitidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
